// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/model.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Checkpoint represent metadata for a dir in user's system with a user defined checkpoint name and other metadata that will be used by rift
type Checkpoint struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	CheckpointName           string                 `protobuf:"bytes,1,opt,name=checkpoint_name,json=checkpointName,proto3" json:"checkpoint_name,omitempty"`                                  // checkpoint name for checkpoint
	CheckpointPath           string                 `protobuf:"bytes,2,opt,name=checkpoint_path,json=checkpointPath,proto3" json:"checkpoint_path,omitempty"`                                  // the actual dir path
	CheckpointAddedAt        string                 `protobuf:"bytes,3,opt,name=checkpoint_added_at,json=checkpointAddedAt,proto3" json:"checkpoint_added_at,omitempty"`                       // when was this checkpoint added
	CheckpointTravelledCount int64                  `protobuf:"varint,4,opt,name=checkpoint_travelled_count,json=checkpointTravelledCount,proto3" json:"checkpoint_travelled_count,omitempty"` // represent how many time user have traveled to this checkpoint
	CheckpointIsSealed       bool                   `protobuf:"varint,5,opt,name=checkpoint_is_sealed,json=checkpointIsSealed,proto3" json:"checkpoint_is_sealed,omitempty"`                   // represent if this checkpoint no longer exist in user's system
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *Checkpoint) Reset() {
	*x = Checkpoint{}
	mi := &file_proto_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Checkpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Checkpoint) ProtoMessage() {}

func (x *Checkpoint) ProtoReflect() protoreflect.Message {
	mi := &file_proto_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Checkpoint.ProtoReflect.Descriptor instead.
func (*Checkpoint) Descriptor() ([]byte, []int) {
	return file_proto_model_proto_rawDescGZIP(), []int{0}
}

func (x *Checkpoint) GetCheckpointName() string {
	if x != nil {
		return x.CheckpointName
	}
	return ""
}

func (x *Checkpoint) GetCheckpointPath() string {
	if x != nil {
		return x.CheckpointPath
	}
	return ""
}

func (x *Checkpoint) GetCheckpointAddedAt() string {
	if x != nil {
		return x.CheckpointAddedAt
	}
	return ""
}

func (x *Checkpoint) GetCheckpointTravelledCount() int64 {
	if x != nil {
		return x.CheckpointTravelledCount
	}
	return 0
}

func (x *Checkpoint) GetCheckpointIsSealed() bool {
	if x != nil {
		return x.CheckpointIsSealed
	}
	return false
}

var File_proto_model_proto protoreflect.FileDescriptor

const file_proto_model_proto_rawDesc = "" +
	"\n" +
	"\x11proto/model.proto\x12\x05store\"\xfe\x01\n" +
	"\n" +
	"Checkpoint\x12'\n" +
	"\x0fcheckpoint_name\x18\x01 \x01(\tR\x0echeckpointName\x12'\n" +
	"\x0fcheckpoint_path\x18\x02 \x01(\tR\x0echeckpointPath\x12.\n" +
	"\x13checkpoint_added_at\x18\x03 \x01(\tR\x11checkpointAddedAt\x12<\n" +
	"\x1acheckpoint_travelled_count\x18\x04 \x01(\x03R\x18checkpointTravelledCount\x120\n" +
	"\x14checkpoint_is_sealed\x18\x05 \x01(\bR\x12checkpointIsSealedB Z\x1egithub.com/gohyuhan/rift/protob\x06proto3"

var (
	file_proto_model_proto_rawDescOnce sync.Once
	file_proto_model_proto_rawDescData []byte
)

func file_proto_model_proto_rawDescGZIP() []byte {
	file_proto_model_proto_rawDescOnce.Do(func() {
		file_proto_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_model_proto_rawDesc), len(file_proto_model_proto_rawDesc)))
	})
	return file_proto_model_proto_rawDescData
}

var file_proto_model_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_model_proto_goTypes = []any{
	(*Checkpoint)(nil), // 0: store.Checkpoint
}
var file_proto_model_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_model_proto_init() }
func file_proto_model_proto_init() {
	if File_proto_model_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_model_proto_rawDesc), len(file_proto_model_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_model_proto_goTypes,
		DependencyIndexes: file_proto_model_proto_depIdxs,
		MessageInfos:      file_proto_model_proto_msgTypes,
	}.Build()
	File_proto_model_proto = out.File
	file_proto_model_proto_goTypes = nil
	file_proto_model_proto_depIdxs = nil
}
