// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/ritual.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RitualCmds struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Commands      []string               `protobuf:"bytes,1,rep,name=commands,proto3" json:"commands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RitualCmds) Reset() {
	*x = RitualCmds{}
	mi := &file_proto_ritual_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RitualCmds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RitualCmds) ProtoMessage() {}

func (x *RitualCmds) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ritual_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RitualCmds.ProtoReflect.Descriptor instead.
func (*RitualCmds) Descriptor() ([]byte, []int) {
	return file_proto_ritual_proto_rawDescGZIP(), []int{0}
}

func (x *RitualCmds) GetCommands() []string {
	if x != nil {
		return x.Commands
	}
	return nil
}

// Ritual represent metadata of commands
type Ritual struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RitualName        string                 `protobuf:"bytes,1,opt,name=ritual_name,json=ritualName,proto3" json:"ritual_name,omitempty"`                         // the assign name of the ritual
	RitualDesc        string                 `protobuf:"bytes,2,opt,name=ritual_desc,json=ritualDesc,proto3" json:"ritual_desc,omitempty"`                         // the summary description of the ritual
	RitualCmds        []*RitualCmds          `protobuf:"bytes,3,rep,name=ritual_cmds,json=ritualCmds,proto3" json:"ritual_cmds,omitempty"`                         // the set of ritual commands
	RitualAddedAt     string                 `protobuf:"bytes,4,opt,name=ritual_added_at,json=ritualAddedAt,proto3" json:"ritual_added_at,omitempty"`              // when was this ritual added
	RitualInvokeCount int64                  `protobuf:"varint,5,opt,name=ritual_invoke_count,json=ritualInvokeCount,proto3" json:"ritual_invoke_count,omitempty"` // represent how many times user have invoke this ritual
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Ritual) Reset() {
	*x = Ritual{}
	mi := &file_proto_ritual_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ritual) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ritual) ProtoMessage() {}

func (x *Ritual) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ritual_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ritual.ProtoReflect.Descriptor instead.
func (*Ritual) Descriptor() ([]byte, []int) {
	return file_proto_ritual_proto_rawDescGZIP(), []int{1}
}

func (x *Ritual) GetRitualName() string {
	if x != nil {
		return x.RitualName
	}
	return ""
}

func (x *Ritual) GetRitualDesc() string {
	if x != nil {
		return x.RitualDesc
	}
	return ""
}

func (x *Ritual) GetRitualCmds() []*RitualCmds {
	if x != nil {
		return x.RitualCmds
	}
	return nil
}

func (x *Ritual) GetRitualAddedAt() string {
	if x != nil {
		return x.RitualAddedAt
	}
	return ""
}

func (x *Ritual) GetRitualInvokeCount() int64 {
	if x != nil {
		return x.RitualInvokeCount
	}
	return 0
}

var File_proto_ritual_proto protoreflect.FileDescriptor

const file_proto_ritual_proto_rawDesc = "" +
	"\n" +
	"\x12proto/ritual.proto\x12\x05proto\"(\n" +
	"\n" +
	"RitualCmds\x12\x1a\n" +
	"\bcommands\x18\x01 \x03(\tR\bcommands\"\xd6\x01\n" +
	"\x06Ritual\x12\x1f\n" +
	"\vritual_name\x18\x01 \x01(\tR\n" +
	"ritualName\x12\x1f\n" +
	"\vritual_desc\x18\x02 \x01(\tR\n" +
	"ritualDesc\x122\n" +
	"\vritual_cmds\x18\x03 \x03(\v2\x11.proto.RitualCmdsR\n" +
	"ritualCmds\x12&\n" +
	"\x0fritual_added_at\x18\x04 \x01(\tR\rritualAddedAt\x12.\n" +
	"\x13ritual_invoke_count\x18\x05 \x01(\x03R\x11ritualInvokeCountB Z\x1egithub.com/gohyuhan/rift/protob\x06proto3"

var (
	file_proto_ritual_proto_rawDescOnce sync.Once
	file_proto_ritual_proto_rawDescData []byte
)

func file_proto_ritual_proto_rawDescGZIP() []byte {
	file_proto_ritual_proto_rawDescOnce.Do(func() {
		file_proto_ritual_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ritual_proto_rawDesc), len(file_proto_ritual_proto_rawDesc)))
	})
	return file_proto_ritual_proto_rawDescData
}

var file_proto_ritual_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_ritual_proto_goTypes = []any{
	(*RitualCmds)(nil), // 0: proto.RitualCmds
	(*Ritual)(nil),     // 1: proto.Ritual
}
var file_proto_ritual_proto_depIdxs = []int32{
	0, // 0: proto.Ritual.ritual_cmds:type_name -> proto.RitualCmds
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_ritual_proto_init() }
func file_proto_ritual_proto_init() {
	if File_proto_ritual_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ritual_proto_rawDesc), len(file_proto_ritual_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_ritual_proto_goTypes,
		DependencyIndexes: file_proto_ritual_proto_depIdxs,
		MessageInfos:      file_proto_ritual_proto_msgTypes,
	}.Build()
	File_proto_ritual_proto = out.File
	file_proto_ritual_proto_goTypes = nil
	file_proto_ritual_proto_depIdxs = nil
}
