// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/rune.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RuneCmds struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Commands      []string               `protobuf:"bytes,1,rep,name=commands,proto3" json:"commands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuneCmds) Reset() {
	*x = RuneCmds{}
	mi := &file_proto_rune_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuneCmds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuneCmds) ProtoMessage() {}

func (x *RuneCmds) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rune_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuneCmds.ProtoReflect.Descriptor instead.
func (*RuneCmds) Descriptor() ([]byte, []int) {
	return file_proto_rune_proto_rawDescGZIP(), []int{0}
}

func (x *RuneCmds) GetCommands() []string {
	if x != nil {
		return x.Commands
	}
	return nil
}

// Rune represent metadata of commands that will be triggered for a dir when it enter or leaves the define path using rift
type Rune struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WaypointPath  string                 `protobuf:"bytes,1,opt,name=waypoint_path,json=waypointPath,proto3" json:"waypoint_path,omitempty"` // the actual dir path that will trigger the rune
	EnterRunes    []*RuneCmds            `protobuf:"bytes,2,rep,name=enter_runes,json=enterRunes,proto3" json:"enter_runes,omitempty"`       // rune that will trigger when using rift to enter a dir
	LeaveRunes    []*RuneCmds            `protobuf:"bytes,3,rep,name=leave_runes,json=leaveRunes,proto3" json:"leave_runes,omitempty"`       // rune that will trigger when using rift to leave a dir
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rune) Reset() {
	*x = Rune{}
	mi := &file_proto_rune_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rune) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rune) ProtoMessage() {}

func (x *Rune) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rune_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rune.ProtoReflect.Descriptor instead.
func (*Rune) Descriptor() ([]byte, []int) {
	return file_proto_rune_proto_rawDescGZIP(), []int{1}
}

func (x *Rune) GetWaypointPath() string {
	if x != nil {
		return x.WaypointPath
	}
	return ""
}

func (x *Rune) GetEnterRunes() []*RuneCmds {
	if x != nil {
		return x.EnterRunes
	}
	return nil
}

func (x *Rune) GetLeaveRunes() []*RuneCmds {
	if x != nil {
		return x.LeaveRunes
	}
	return nil
}

var File_proto_rune_proto protoreflect.FileDescriptor

const file_proto_rune_proto_rawDesc = "" +
	"\n" +
	"\x10proto/rune.proto\x12\x05proto\"&\n" +
	"\bRuneCmds\x12\x1a\n" +
	"\bcommands\x18\x01 \x03(\tR\bcommands\"\x8f\x01\n" +
	"\x04Rune\x12#\n" +
	"\rwaypoint_path\x18\x01 \x01(\tR\fwaypointPath\x120\n" +
	"\venter_runes\x18\x02 \x03(\v2\x0f.proto.RuneCmdsR\n" +
	"enterRunes\x120\n" +
	"\vleave_runes\x18\x03 \x03(\v2\x0f.proto.RuneCmdsR\n" +
	"leaveRunesB Z\x1egithub.com/gohyuhan/rift/protob\x06proto3"

var (
	file_proto_rune_proto_rawDescOnce sync.Once
	file_proto_rune_proto_rawDescData []byte
)

func file_proto_rune_proto_rawDescGZIP() []byte {
	file_proto_rune_proto_rawDescOnce.Do(func() {
		file_proto_rune_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_rune_proto_rawDesc), len(file_proto_rune_proto_rawDesc)))
	})
	return file_proto_rune_proto_rawDescData
}

var file_proto_rune_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_rune_proto_goTypes = []any{
	(*RuneCmds)(nil), // 0: proto.RuneCmds
	(*Rune)(nil),     // 1: proto.Rune
}
var file_proto_rune_proto_depIdxs = []int32{
	0, // 0: proto.Rune.enter_runes:type_name -> proto.RuneCmds
	0, // 1: proto.Rune.leave_runes:type_name -> proto.RuneCmds
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_rune_proto_init() }
func file_proto_rune_proto_init() {
	if File_proto_rune_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_rune_proto_rawDesc), len(file_proto_rune_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_rune_proto_goTypes,
		DependencyIndexes: file_proto_rune_proto_depIdxs,
		MessageInfos:      file_proto_rune_proto_msgTypes,
	}.Build()
	File_proto_rune_proto = out.File
	file_proto_rune_proto_goTypes = nil
	file_proto_rune_proto_depIdxs = nil
}
