// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/spell.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// spell represent metadata for a terminal command with a user defined spell name and other metadata that will be used by rift
type Spell struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SpellName      string                 `protobuf:"bytes,1,opt,name=spell_name,json=spellName,proto3" json:"spell_name,omitempty"`                   // name for the spell
	SpellCommand   []string               `protobuf:"bytes,2,rep,name=spell_command,json=spellCommand,proto3" json:"spell_command,omitempty"`          // the terminal command split into an array of arguments
	SpellAddedAt   string                 `protobuf:"bytes,3,opt,name=spell_added_at,json=spellAddedAt,proto3" json:"spell_added_at,omitempty"`        // when was this spell added
	SpellCastCount int64                  `protobuf:"varint,4,opt,name=spell_cast_count,json=spellCastCount,proto3" json:"spell_cast_count,omitempty"` // represent how many times user have cast this spell
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Spell) Reset() {
	*x = Spell{}
	mi := &file_proto_spell_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Spell) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Spell) ProtoMessage() {}

func (x *Spell) ProtoReflect() protoreflect.Message {
	mi := &file_proto_spell_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Spell.ProtoReflect.Descriptor instead.
func (*Spell) Descriptor() ([]byte, []int) {
	return file_proto_spell_proto_rawDescGZIP(), []int{0}
}

func (x *Spell) GetSpellName() string {
	if x != nil {
		return x.SpellName
	}
	return ""
}

func (x *Spell) GetSpellCommand() []string {
	if x != nil {
		return x.SpellCommand
	}
	return nil
}

func (x *Spell) GetSpellAddedAt() string {
	if x != nil {
		return x.SpellAddedAt
	}
	return ""
}

func (x *Spell) GetSpellCastCount() int64 {
	if x != nil {
		return x.SpellCastCount
	}
	return 0
}

var File_proto_spell_proto protoreflect.FileDescriptor

const file_proto_spell_proto_rawDesc = "" +
	"\n" +
	"\x11proto/spell.proto\x12\x05proto\"\x9b\x01\n" +
	"\x05Spell\x12\x1d\n" +
	"\n" +
	"spell_name\x18\x01 \x01(\tR\tspellName\x12#\n" +
	"\rspell_command\x18\x02 \x03(\tR\fspellCommand\x12$\n" +
	"\x0espell_added_at\x18\x03 \x01(\tR\fspellAddedAt\x12(\n" +
	"\x10spell_cast_count\x18\x04 \x01(\x03R\x0espellCastCountB Z\x1egithub.com/gohyuhan/rift/protob\x06proto3"

var (
	file_proto_spell_proto_rawDescOnce sync.Once
	file_proto_spell_proto_rawDescData []byte
)

func file_proto_spell_proto_rawDescGZIP() []byte {
	file_proto_spell_proto_rawDescOnce.Do(func() {
		file_proto_spell_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_spell_proto_rawDesc), len(file_proto_spell_proto_rawDesc)))
	})
	return file_proto_spell_proto_rawDescData
}

var file_proto_spell_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_spell_proto_goTypes = []any{
	(*Spell)(nil), // 0: proto.Spell
}
var file_proto_spell_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_spell_proto_init() }
func file_proto_spell_proto_init() {
	if File_proto_spell_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_spell_proto_rawDesc), len(file_proto_spell_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_spell_proto_goTypes,
		DependencyIndexes: file_proto_spell_proto_depIdxs,
		MessageInfos:      file_proto_spell_proto_msgTypes,
	}.Build()
	File_proto_spell_proto = out.File
	file_proto_spell_proto_goTypes = nil
	file_proto_spell_proto_depIdxs = nil
}
