// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/waypoint.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Rune struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Commands      []string               `protobuf:"bytes,1,rep,name=commands,proto3" json:"commands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rune) Reset() {
	*x = Rune{}
	mi := &file_proto_waypoint_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rune) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rune) ProtoMessage() {}

func (x *Rune) ProtoReflect() protoreflect.Message {
	mi := &file_proto_waypoint_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rune.ProtoReflect.Descriptor instead.
func (*Rune) Descriptor() ([]byte, []int) {
	return file_proto_waypoint_proto_rawDescGZIP(), []int{0}
}

func (x *Rune) GetCommands() []string {
	if x != nil {
		return x.Commands
	}
	return nil
}

// waypoint represent metadata for a dir in user's system with a user defined waypoint name and other metadata that will be used by rift
type Waypoint struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	WaypointName           string                 `protobuf:"bytes,1,opt,name=waypoint_name,json=waypointName,proto3" json:"waypoint_name,omitempty"`                                  // waypoint name for waypoint
	WaypointPath           string                 `protobuf:"bytes,2,opt,name=waypoint_path,json=waypointPath,proto3" json:"waypoint_path,omitempty"`                                  // the actual dir path
	WaypointAddedAt        string                 `protobuf:"bytes,3,opt,name=waypoint_added_at,json=waypointAddedAt,proto3" json:"waypoint_added_at,omitempty"`                       // when was this waypoint added
	WaypointTravelledCount int64                  `protobuf:"varint,4,opt,name=waypoint_travelled_count,json=waypointTravelledCount,proto3" json:"waypoint_travelled_count,omitempty"` // represent how many time user have traveled to this waypoint
	WaypointIsSealed       bool                   `protobuf:"varint,5,opt,name=waypoint_is_sealed,json=waypointIsSealed,proto3" json:"waypoint_is_sealed,omitempty"`                   // represent if this waypoint no longer exist in user's system
	WaypointSealedReason   string                 `protobuf:"bytes,6,opt,name=waypoint_sealed_reason,json=waypointSealedReason,proto3" json:"waypoint_sealed_reason,omitempty"`
	EnterRunes             []*Rune                `protobuf:"bytes,7,rep,name=enter_runes,json=enterRunes,proto3" json:"enter_runes,omitempty"` // rune that will trigger when using rift to enter a dir
	LeaveRunes             []*Rune                `protobuf:"bytes,8,rep,name=leave_runes,json=leaveRunes,proto3" json:"leave_runes,omitempty"` // rune that will trigger when using rift to leave a dir
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Waypoint) Reset() {
	*x = Waypoint{}
	mi := &file_proto_waypoint_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Waypoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Waypoint) ProtoMessage() {}

func (x *Waypoint) ProtoReflect() protoreflect.Message {
	mi := &file_proto_waypoint_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Waypoint.ProtoReflect.Descriptor instead.
func (*Waypoint) Descriptor() ([]byte, []int) {
	return file_proto_waypoint_proto_rawDescGZIP(), []int{1}
}

func (x *Waypoint) GetWaypointName() string {
	if x != nil {
		return x.WaypointName
	}
	return ""
}

func (x *Waypoint) GetWaypointPath() string {
	if x != nil {
		return x.WaypointPath
	}
	return ""
}

func (x *Waypoint) GetWaypointAddedAt() string {
	if x != nil {
		return x.WaypointAddedAt
	}
	return ""
}

func (x *Waypoint) GetWaypointTravelledCount() int64 {
	if x != nil {
		return x.WaypointTravelledCount
	}
	return 0
}

func (x *Waypoint) GetWaypointIsSealed() bool {
	if x != nil {
		return x.WaypointIsSealed
	}
	return false
}

func (x *Waypoint) GetWaypointSealedReason() string {
	if x != nil {
		return x.WaypointSealedReason
	}
	return ""
}

func (x *Waypoint) GetEnterRunes() []*Rune {
	if x != nil {
		return x.EnterRunes
	}
	return nil
}

func (x *Waypoint) GetLeaveRunes() []*Rune {
	if x != nil {
		return x.LeaveRunes
	}
	return nil
}

var File_proto_waypoint_proto protoreflect.FileDescriptor

const file_proto_waypoint_proto_rawDesc = "" +
	"\n" +
	"\x14proto/waypoint.proto\x12\x05proto\"\"\n" +
	"\x04Rune\x12\x1a\n" +
	"\bcommands\x18\x01 \x03(\tR\bcommands\"\xfa\x02\n" +
	"\bWaypoint\x12#\n" +
	"\rwaypoint_name\x18\x01 \x01(\tR\fwaypointName\x12#\n" +
	"\rwaypoint_path\x18\x02 \x01(\tR\fwaypointPath\x12*\n" +
	"\x11waypoint_added_at\x18\x03 \x01(\tR\x0fwaypointAddedAt\x128\n" +
	"\x18waypoint_travelled_count\x18\x04 \x01(\x03R\x16waypointTravelledCount\x12,\n" +
	"\x12waypoint_is_sealed\x18\x05 \x01(\bR\x10waypointIsSealed\x124\n" +
	"\x16waypoint_sealed_reason\x18\x06 \x01(\tR\x14waypointSealedReason\x12,\n" +
	"\venter_runes\x18\a \x03(\v2\v.proto.RuneR\n" +
	"enterRunes\x12,\n" +
	"\vleave_runes\x18\b \x03(\v2\v.proto.RuneR\n" +
	"leaveRunesB Z\x1egithub.com/gohyuhan/rift/protob\x06proto3"

var (
	file_proto_waypoint_proto_rawDescOnce sync.Once
	file_proto_waypoint_proto_rawDescData []byte
)

func file_proto_waypoint_proto_rawDescGZIP() []byte {
	file_proto_waypoint_proto_rawDescOnce.Do(func() {
		file_proto_waypoint_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_waypoint_proto_rawDesc), len(file_proto_waypoint_proto_rawDesc)))
	})
	return file_proto_waypoint_proto_rawDescData
}

var file_proto_waypoint_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_waypoint_proto_goTypes = []any{
	(*Rune)(nil),     // 0: proto.Rune
	(*Waypoint)(nil), // 1: proto.Waypoint
}
var file_proto_waypoint_proto_depIdxs = []int32{
	0, // 0: proto.Waypoint.enter_runes:type_name -> proto.Rune
	0, // 1: proto.Waypoint.leave_runes:type_name -> proto.Rune
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_waypoint_proto_init() }
func file_proto_waypoint_proto_init() {
	if File_proto_waypoint_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_waypoint_proto_rawDesc), len(file_proto_waypoint_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_waypoint_proto_goTypes,
		DependencyIndexes: file_proto_waypoint_proto_depIdxs,
		MessageInfos:      file_proto_waypoint_proto_msgTypes,
	}.Build()
	File_proto_waypoint_proto = out.File
	file_proto_waypoint_proto_goTypes = nil
	file_proto_waypoint_proto_depIdxs = nil
}
